# Generated by Django 5.0.2 on 2025-05-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('ACADEMIC', 'Academic'), ('EVENT', 'Event'), ('EXAM', 'Examination'), ('RESULT', 'Result'), ('HOLIDAY', 'Holiday'), ('ADMISSION', 'Admission'), ('PLACEMENT', 'Placement'), ('OTHER', 'Other')], default='ACADEMIC', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IT', 'Information Technology'), ('AI', 'Artificial Intelligence'), ('DS', 'Data Science'), ('GENERAL', 'General')], max_length=20),
        ),
    ]
